export type Family =
  | "Nonmetal"
  | "Noble Gas"
  | "Alkali Metal"
  | "Alkaline Earth Metal"
  | "Metalloid"
  | "Halogen"
  | "Lanthanide"
  | "Actinide"
  | "Transition Metal"
  | "Metal";

export interface ChemistryElement {
  name: string;
  atomicNumber: number;
  atomicSymbol: string;
  radioactive?: true;
  family: Family;
  positiveIon?: number;
  negativeIon?: number;
  /** Atomic mass divided by 100 rounded up. */
  massGroup: number;
}

export const gameData: ReadonlyArray<Readonly<ChemistryElement>> = [
  {
    name: "Hydrogen",
    atomicNumber: 1,
    atomicSymbol: "H",
    family: "Nonmetal",
    positiveIon: 1,
    negativeIon: 1,
    massGroup: 1,
  },
  {
    name: "Helium",
    atomicNumber: 2,
    atomicSymbol: "He",
    family: "Noble Gas",
    massGroup: 1,
  },
  {
    name: "Lithium",
    atomicNumber: 3,
    atomicSymbol: "Li",
    family: "Alkali Metal",
    positiveIon: 1,
    massGroup: 1,
  },
  {
    name: "Beryllium",
    atomicNumber: 4,
    atomicSymbol: "Be",
    family: "Alkaline Earth Metal",
    positiveIon: 2,
    massGroup: 1,
  },
  {
    name: "Boron",
    atomicNumber: 5,
    atomicSymbol: "B",
    family: "Metalloid",
    massGroup: 1,
  },
  {
    name: "Carbon",
    atomicNumber: 6,
    atomicSymbol: "C",
    family: "Nonmetal",
    massGroup: 1,
  },
  {
    name: "Nitrogen",
    atomicNumber: 7,
    atomicSymbol: "N",
    family: "Nonmetal",
    negativeIon: 3,
    massGroup: 1,
  },
  {
    name: "Oxygen",
    atomicNumber: 8,
    atomicSymbol: "O",
    family: "Nonmetal",
    negativeIon: 2,
    massGroup: 1,
  },
  {
    name: "Fluorine",
    atomicNumber: 9,
    atomicSymbol: "F",
    family: "Halogen",
    negativeIon: 1,
    massGroup: 1,
  },
  {
    name: "Neon",
    atomicNumber: 10,
    atomicSymbol: "Ne",
    family: "Noble Gas",
    massGroup: 1,
  },
  {
    name: "Sodium",
    atomicNumber: 11,
    atomicSymbol: "Na",
    family: "Alkali Metal",
    positiveIon: 1,
    massGroup: 1,
  },
  {
    name: "Magnesium",
    atomicNumber: 12,
    atomicSymbol: "Mg",
    family: "Alkaline Earth Metal",
    positiveIon: 2,
    massGroup: 1,
  },
  {
    name: "Aluminum",
    atomicNumber: 13,
    atomicSymbol: "Al",
    family: "Metal",
    positiveIon: 3,
    massGroup: 1,
  },
  {
    name: "Silicon",
    atomicNumber: 14,
    atomicSymbol: "Si",
    family: "Metalloid",
    massGroup: 1,
  },
  {
    name: "Phosphorus",
    atomicNumber: 15,
    atomicSymbol: "P",
    family: "Nonmetal",
    negativeIon: 3,
    massGroup: 1,
  },
  {
    name: "Sulfur",
    atomicNumber: 16,
    atomicSymbol: "S",
    family: "Nonmetal",
    negativeIon: 2,
    massGroup: 1,
  },
  {
    name: "Chlorine",
    atomicNumber: 17,
    atomicSymbol: "Cl",
    family: "Halogen",
    negativeIon: 1,
    massGroup: 1,
  },
  {
    name: "Argon",
    atomicNumber: 18,
    atomicSymbol: "Ar",
    family: "Noble Gas",
    massGroup: 1,
  },
  {
    name: "Potassium",
    atomicNumber: 19,
    atomicSymbol: "K",
    family: "Alkali Metal",
    positiveIon: 1,
    massGroup: 1,
  },
  {
    name: "Calcium",
    atomicNumber: 20,
    atomicSymbol: "Ca",
    family: "Alkaline Earth Metal",
    positiveIon: 2,
    massGroup: 1,
  },
  {
    name: "Scandium",
    atomicNumber: 21,
    atomicSymbol: "Sc",
    family: "Transition Metal",
    positiveIon: 3,
    massGroup: 1,
  },
  {
    name: "Titanium",
    atomicNumber: 22,
    atomicSymbol: "Ti",
    family: "Transition Metal",
    massGroup: 1,
  },
  {
    name: "Vanadium",
    atomicNumber: 23,
    atomicSymbol: "V",
    family: "Transition Metal",
    massGroup: 1,
  },
  {
    name: "Chromium",
    atomicNumber: 24,
    atomicSymbol: "Cr",
    family: "Transition Metal",
    massGroup: 1,
  },
  {
    name: "Manganese",
    atomicNumber: 25,
    atomicSymbol: "Mn",
    family: "Transition Metal",
    massGroup: 1,
  },
  {
    name: "Iron",
    atomicNumber: 26,
    atomicSymbol: "Fe",
    family: "Transition Metal",
    massGroup: 1,
  },
  {
    name: "Cobalt",
    atomicNumber: 27,
    atomicSymbol: "Co",
    family: "Transition Metal",
    massGroup: 1,
  },
  {
    name: "Nickel",
    atomicNumber: 28,
    atomicSymbol: "Ni",
    family: "Transition Metal",
    massGroup: 1,
  },
  {
    name: "Copper",
    atomicNumber: 29,
    atomicSymbol: "Cu",
    family: "Transition Metal",
    massGroup: 1,
  },
  {
    name: "Zinc",
    atomicNumber: 30,
    atomicSymbol: "Zn",
    family: "Transition Metal",
    massGroup: 1,
  },
  {
    name: "Gallium",
    atomicNumber: 31,
    atomicSymbol: "Ga",
    family: "Metal",
    massGroup: 1,
  },
  {
    name: "Germanium",
    atomicNumber: 32,
    atomicSymbol: "Ge",
    family: "Metalloid",
    massGroup: 1,
  },
  {
    name: "Arsenic",
    atomicNumber: 33,
    atomicSymbol: "As",
    family: "Metalloid",
    negativeIon: 3,
    massGroup: 1,
  },
  {
    name: "Selenium",
    atomicNumber: 34,
    atomicSymbol: "Se",
    family: "Nonmetal",
    negativeIon: 2,
    massGroup: 1,
  },
  {
    name: "Bromine",
    atomicNumber: 35,
    atomicSymbol: "Br",
    family: "Halogen",
    negativeIon: 1,
    massGroup: 1,
  },
  {
    name: "Krypton",
    atomicNumber: 36,
    atomicSymbol: "Kr",
    family: "Noble Gas",
    massGroup: 1,
  },
  {
    name: "Rubidium",
    atomicNumber: 37,
    atomicSymbol: "Rb",
    family: "Alkali Metal",
    positiveIon: 1,
    massGroup: 1,
  },
  {
    name: "Strontium",
    atomicNumber: 38,
    atomicSymbol: "Sr",
    family: "Alkaline Earth Metal",
    positiveIon: 2,
    massGroup: 1,
  },
  {
    name: "Yttrium",
    atomicNumber: 39,
    atomicSymbol: "Y",
    family: "Transition Metal",
    positiveIon: 3,
    massGroup: 1,
  },
  {
    name: "Zirconium",
    atomicNumber: 40,
    atomicSymbol: "Zr",
    family: "Transition Metal",
    massGroup: 1,
  },
  {
    name: "Niobium",
    atomicNumber: 41,
    atomicSymbol: "Nb",
    family: "Transition Metal",
    massGroup: 1,
  },
  {
    name: "Molybdenum",
    atomicNumber: 42,
    atomicSymbol: "Mo",
    family: "Transition Metal",
    massGroup: 1,
  },
  {
    name: "Technetium",
    atomicNumber: 43,
    atomicSymbol: "Tc",
    radioactive: true,
    family: "Transition Metal",
    massGroup: 1,
  },
  {
    name: "Ruthenium",
    atomicNumber: 44,
    atomicSymbol: "Ru",
    family: "Transition Metal",
    massGroup: 2,
  },
  {
    name: "Rhodium",
    atomicNumber: 45,
    atomicSymbol: "Rh",
    family: "Transition Metal",
    massGroup: 2,
  },
  {
    name: "Palladium",
    atomicNumber: 46,
    atomicSymbol: "Pd",
    family: "Transition Metal",
    massGroup: 2,
  },
  {
    name: "Silver",
    atomicNumber: 47,
    atomicSymbol: "Ag",
    family: "Transition Metal",
    massGroup: 2,
  },
  {
    name: "Cadmium",
    atomicNumber: 48,
    atomicSymbol: "Cd",
    family: "Transition Metal",
    massGroup: 2,
  },
  {
    name: "Indium",
    atomicNumber: 49,
    atomicSymbol: "In",
    family: "Metal",
    massGroup: 2,
  },
  {
    name: "Tin",
    atomicNumber: 50,
    atomicSymbol: "Sn",
    family: "Metal",
    massGroup: 2,
  },
  {
    name: "Antimony",
    atomicNumber: 51,
    atomicSymbol: "Sb",
    family: "Metalloid",
    massGroup: 2,
  },
  {
    name: "Tellurium",
    atomicNumber: 52,
    atomicSymbol: "Te",
    family: "Metalloid",
    negativeIon: 2,
    massGroup: 2,
  },
  {
    name: "Iodine",
    atomicNumber: 53,
    atomicSymbol: "I",
    family: "Halogen",
    negativeIon: 1,
    massGroup: 2,
  },
  {
    name: "Xenon",
    atomicNumber: 54,
    atomicSymbol: "Xe",
    family: "Noble Gas",
    massGroup: 2,
  },
  {
    name: "Cesium",
    atomicNumber: 55,
    atomicSymbol: "Cs",
    family: "Alkali Metal",
    positiveIon: 1,
    massGroup: 2,
  },
  {
    name: "Barium",
    atomicNumber: 56,
    atomicSymbol: "Ba",
    family: "Alkaline Earth Metal",
    positiveIon: 2,
    massGroup: 2,
  },
  {
    name: "Lanthanum",
    atomicNumber: 57,
    atomicSymbol: "La",
    family: "Lanthanide",
    positiveIon: 3,
    massGroup: 2,
  },
  {
    name: "Cerium",
    atomicNumber: 58,
    atomicSymbol: "Ce",
    family: "Lanthanide",
    massGroup: 2,
  },
  {
    name: "Praseodymium",
    atomicNumber: 59,
    atomicSymbol: "Pr",
    family: "Lanthanide",
    massGroup: 2,
  },
  {
    name: "Neodymium",
    atomicNumber: 60,
    atomicSymbol: "Nd",
    family: "Lanthanide",
    massGroup: 2,
  },
  {
    name: "Promethium",
    atomicNumber: 61,
    atomicSymbol: "Pm",
    radioactive: true,
    family: "Lanthanide",
    massGroup: 2,
  },
  {
    name: "Samarium",
    atomicNumber: 62,
    atomicSymbol: "Sm",
    family: "Lanthanide",
    massGroup: 2,
  },
  {
    name: "Europium",
    atomicNumber: 63,
    atomicSymbol: "Eu",
    family: "Lanthanide",
    massGroup: 2,
  },
  {
    name: "Gadolinium",
    atomicNumber: 64,
    atomicSymbol: "Gd",
    family: "Lanthanide",
    massGroup: 2,
  },
  {
    name: "Terbium",
    atomicNumber: 65,
    atomicSymbol: "Tb",
    family: "Lanthanide",
    massGroup: 2,
  },
  {
    name: "Dysprosium",
    atomicNumber: 66,
    atomicSymbol: "Dy",
    family: "Lanthanide",
    massGroup: 2,
  },
  {
    name: "Holmium",
    atomicNumber: 67,
    atomicSymbol: "Ho",
    family: "Lanthanide",
    massGroup: 2,
  },
  {
    name: "Erbium",
    atomicNumber: 68,
    atomicSymbol: "Er",
    family: "Lanthanide",
    massGroup: 2,
  },
  {
    name: "Thulium",
    atomicNumber: 69,
    atomicSymbol: "Tm",
    family: "Lanthanide",
    massGroup: 2,
  },
  {
    name: "Ytterbium",
    atomicNumber: 70,
    atomicSymbol: "Yb",
    family: "Lanthanide",
    massGroup: 2,
  },
  {
    name: "Lutetium",
    atomicNumber: 71,
    atomicSymbol: "Lu",
    family: "Lanthanide",
    massGroup: 2,
  },
  {
    name: "Hafnium",
    atomicNumber: 72,
    atomicSymbol: "Hf",
    family: "Transition Metal",
    massGroup: 2,
  },
  {
    name: "Tantalum",
    atomicNumber: 73,
    atomicSymbol: "Ta",
    family: "Transition Metal",
    massGroup: 2,
  },
  {
    name: "Tungsten",
    atomicNumber: 74,
    atomicSymbol: "W",
    family: "Transition Metal",
    massGroup: 2,
  },
  {
    name: "Rhenium",
    atomicNumber: 75,
    atomicSymbol: "Re",
    family: "Transition Metal",
    massGroup: 2,
  },
  {
    name: "Osmium",
    atomicNumber: 76,
    atomicSymbol: "Os",
    family: "Transition Metal",
    massGroup: 2,
  },
  {
    name: "Iridium",
    atomicNumber: 77,
    atomicSymbol: "Ir",
    family: "Transition Metal",
    massGroup: 2,
  },
  {
    name: "Platinum",
    atomicNumber: 78,
    atomicSymbol: "Pt",
    family: "Transition Metal",
    massGroup: 2,
  },
  {
    name: "Gold",
    atomicNumber: 79,
    atomicSymbol: "Au",
    family: "Transition Metal",
    massGroup: 2,
  },
  {
    name: "Mercury",
    atomicNumber: 80,
    atomicSymbol: "Hg",
    family: "Transition Metal",
    massGroup: 3,
  },
  {
    name: "Thallium",
    atomicNumber: 81,
    atomicSymbol: "Tl",
    family: "Metal",
    massGroup: 3,
  },
  {
    name: "Lead",
    atomicNumber: 82,
    atomicSymbol: "Pb",
    family: "Metal",
    massGroup: 3,
  },
  {
    name: "Bismuth",
    atomicNumber: 83,
    atomicSymbol: "Bi",
    family: "Metal",
    massGroup: 3,
  },
  {
    name: "Polonium",
    atomicNumber: 84,
    atomicSymbol: "Po",
    radioactive: true,
    family: "Metalloid",
    massGroup: 3,
  },
  {
    name: "Astatine",
    atomicNumber: 85,
    atomicSymbol: "At",
    radioactive: true,
    family: "Noble Gas",
    negativeIon: 1,
    massGroup: 3,
  },
  {
    name: "Radon",
    atomicNumber: 86,
    atomicSymbol: "Rn",
    radioactive: true,
    family: "Alkali Metal",
    massGroup: 3,
  },
  {
    name: "Francium",
    atomicNumber: 87,
    atomicSymbol: "Fr",
    radioactive: true,
    family: "Alkaline Earth Metal",
    positiveIon: 1,
    massGroup: 3,
  },
  {
    name: "Radium",
    atomicNumber: 88,
    atomicSymbol: "Ra",
    radioactive: true,
    family: "Actinide",
    positiveIon: 2,
    massGroup: 3,
  },
  {
    name: "Actinium",
    atomicNumber: 89,
    atomicSymbol: "Ac",
    radioactive: true,
    family: "Actinide",
    positiveIon: 3,
    massGroup: 3,
  },
  {
    name: "Thorium",
    atomicNumber: 90,
    atomicSymbol: "Th",
    radioactive: true,
    family: "Actinide",
    massGroup: 3,
  },
  {
    name: "Protactinium",
    atomicNumber: 91,
    atomicSymbol: "Pa",
    radioactive: true,
    family: "Actinide",
    massGroup: 3,
  },
  {
    name: "Uranium",
    atomicNumber: 92,
    atomicSymbol: "U",
    radioactive: true,
    family: "Actinide",
    massGroup: 3,
  },
  {
    name: "Neptunium",
    atomicNumber: 93,
    atomicSymbol: "Np",
    radioactive: true,
    family: "Actinide",
    massGroup: 3,
  },
  {
    name: "Plutonium",
    atomicNumber: 94,
    atomicSymbol: "Pu",
    radioactive: true,
    family: "Actinide",
    massGroup: 3,
  },
  {
    name: "Americium",
    atomicNumber: 95,
    atomicSymbol: "Am",
    radioactive: true,
    family: "Actinide",
    massGroup: 3,
  },
  {
    name: "Curium",
    atomicNumber: 96,
    atomicSymbol: "Cm",
    radioactive: true,
    family: "Actinide",
    massGroup: 3,
  },
  {
    name: "Berkelium",
    atomicNumber: 97,
    atomicSymbol: "Bk",
    radioactive: true,
    family: "Actinide",
    massGroup: 3,
  },
  {
    name: "Californium",
    atomicNumber: 98,
    atomicSymbol: "Cf",
    radioactive: true,
    family: "Actinide",
    massGroup: 3,
  },
  {
    name: "Einsteinium",
    atomicNumber: 99,
    atomicSymbol: "Es",
    radioactive: true,
    family: "Actinide",
    massGroup: 3,
  },
  {
    name: "Fermium",
    atomicNumber: 100,
    atomicSymbol: "Fm",
    radioactive: true,
    family: "Actinide",
    massGroup: 3,
  },
  {
    name: "Mendelevium",
    atomicNumber: 101,
    atomicSymbol: "Md",
    radioactive: true,
    family: "Actinide",
    massGroup: 3,
  },
  {
    name: "Nobelium",
    atomicNumber: 102,
    atomicSymbol: "No",
    radioactive: true,
    family: "Actinide",
    massGroup: 3,
  },
  {
    name: "Lawrencium",
    atomicNumber: 103,
    atomicSymbol: "Lr",
    radioactive: true,
    family: "Actinide",
    massGroup: 3,
  },
];
