export type Family =
  | "Nonmetal"
  | "Noble Gas"
  | "Alkali Metal"
  | "Alkaline Earth Metal"
  | "Metalloid"
  | "Halogen"
  | "Lanthanide"
  | "Actinide"
  | "Transition Metal"
  | "Metal";

export interface ChemistryElement {
  name: string;
  atomicNumber: number;
  atomicSymbol: string;
  atomicWeight: number;
  radioactive?: true;
  family: Family;
  positiveIon?: number;
  negativeIon?: number;
}

/** Get element by atomic number using efficient lookup. */
export function getElementByAtomicNumber(
  atomicNumber: number
): ChemistryElement {
  const element = elementLookup[atomicNumber];
  if (!element) {
    throw new Error(`Element with atomic number ${atomicNumber} not found`);
  }
  return element;
}

const _gameData: ChemistryElement[] = [
  {
    name: "Hydrogen",
    atomicNumber: 1,
    atomicSymbol: "H",
    atomicWeight: 1.007,
    family: "Nonmetal",
    positiveIon: 1,
  },
  {
    name: "Helium",
    atomicNumber: 2,
    atomicSymbol: "He",
    atomicWeight: 4.002,
    family: "Noble Gas",
  },
  {
    name: "Lithium",
    atomicNumber: 3,
    atomicSymbol: "Li",
    atomicWeight: 6.941,
    family: "Alkali Metal",
    positiveIon: 1,
  },
  {
    name: "Beryllium",
    atomicNumber: 4,
    atomicSymbol: "Be",
    atomicWeight: 9.012,
    family: "Alkaline Earth Metal",
    positiveIon: 2,
  },
  {
    name: "Boron",
    atomicNumber: 5,
    atomicSymbol: "B",
    atomicWeight: 10.811,
    family: "Metalloid",
  },
  {
    name: "Carbon",
    atomicNumber: 6,
    atomicSymbol: "C",
    atomicWeight: 12.011,
    family: "Nonmetal",
  },
  {
    name: "Nitrogen",
    atomicNumber: 7,
    atomicSymbol: "N",
    atomicWeight: 14.007,
    family: "Nonmetal",
    negativeIon: 3,
  },
  {
    name: "Oxygen",
    atomicNumber: 8,
    atomicSymbol: "O",
    atomicWeight: 15.999,
    family: "Nonmetal",
    negativeIon: 2,
  },
  {
    name: "Fluorine",
    atomicNumber: 9,
    atomicSymbol: "F",
    atomicWeight: 18.998,
    family: "Halogen",
    negativeIon: 1,
  },
  {
    name: "Neon",
    atomicNumber: 10,
    atomicSymbol: "Ne",
    atomicWeight: 20.18,
    family: "Noble Gas",
  },
  {
    name: "Sodium",
    atomicNumber: 11,
    atomicSymbol: "Na",
    atomicWeight: 22.99,
    family: "Alkali Metal",
    positiveIon: 1,
  },
  {
    name: "Magnesium",
    atomicNumber: 12,
    atomicSymbol: "Mg",
    atomicWeight: 24.305,
    family: "Alkaline Earth Metal",
    positiveIon: 2,
  },
  {
    name: "Aluminum",
    atomicNumber: 13,
    atomicSymbol: "Al",
    atomicWeight: 26.982,
    family: "Metal",
    positiveIon: 3,
  },
  {
    name: "Silicon",
    atomicNumber: 14,
    atomicSymbol: "Si",
    atomicWeight: 28.086,
    family: "Metalloid",
  },
  {
    name: "Phosphorus",
    atomicNumber: 15,
    atomicSymbol: "P",
    atomicWeight: 30.974,
    family: "Nonmetal",
    negativeIon: 3,
  },
  {
    name: "Sulfur",
    atomicNumber: 16,
    atomicSymbol: "S",
    atomicWeight: 32.065,
    family: "Nonmetal",
    negativeIon: 2,
  },
  {
    name: "Chlorine",
    atomicNumber: 17,
    atomicSymbol: "Cl",
    atomicWeight: 35.453,
    family: "Halogen",
    negativeIon: 1,
  },
  {
    name: "Argon",
    atomicNumber: 18,
    atomicSymbol: "Ar",
    atomicWeight: 39.948,
    family: "Noble Gas",
  },
  {
    name: "Potassium",
    atomicNumber: 19,
    atomicSymbol: "K",
    atomicWeight: 39.098,
    family: "Alkali Metal",
    positiveIon: 1,
  },
  {
    name: "Calcium",
    atomicNumber: 20,
    atomicSymbol: "Ca",
    atomicWeight: 40.078,
    family: "Alkaline Earth Metal",
    positiveIon: 2,
  },
  {
    name: "Scandium",
    atomicNumber: 21,
    atomicSymbol: "Sc",
    atomicWeight: 44.956,
    family: "Transition Metal",
    positiveIon: 3,
  },
  {
    name: "Titanium",
    atomicNumber: 22,
    atomicSymbol: "Ti",
    atomicWeight: 47.867,
    family: "Transition Metal",
  },
  {
    name: "Vanadium",
    atomicNumber: 23,
    atomicSymbol: "V",
    atomicWeight: 50.942,
    family: "Transition Metal",
  },
  {
    name: "Chromium",
    atomicNumber: 24,
    atomicSymbol: "Cr",
    atomicWeight: 51.996,
    family: "Transition Metal",
  },
  {
    name: "Manganese",
    atomicNumber: 25,
    atomicSymbol: "Mn",
    atomicWeight: 54.938,
    family: "Transition Metal",
  },
  {
    name: "Iron",
    atomicNumber: 26,
    atomicSymbol: "Fe",
    atomicWeight: 55.845,
    family: "Transition Metal",
  },
  {
    name: "Cobalt",
    atomicNumber: 27,
    atomicSymbol: "Co",
    atomicWeight: 58.933,
    family: "Transition Metal",
  },
  {
    name: "Nickel",
    atomicNumber: 28,
    atomicSymbol: "Ni",
    atomicWeight: 58.693,
    family: "Transition Metal",
  },
  {
    name: "Copper",
    atomicNumber: 29,
    atomicSymbol: "Cu",
    atomicWeight: 63.546,
    family: "Transition Metal",
  },
  {
    name: "Zinc",
    atomicNumber: 30,
    atomicSymbol: "Zn",
    atomicWeight: 65.38,
    family: "Transition Metal",
    positiveIon: 2,
  },
  {
    name: "Gallium",
    atomicNumber: 31,
    atomicSymbol: "Ga",
    atomicWeight: 69.723,
    family: "Metal",
    positiveIon: 3,
  },
  {
    name: "Germanium",
    atomicNumber: 32,
    atomicSymbol: "Ge",
    atomicWeight: 72.64,
    family: "Metalloid",
  },
  {
    name: "Arsenic",
    atomicNumber: 33,
    atomicSymbol: "As",
    atomicWeight: 74.922,
    family: "Metalloid",
    negativeIon: 3,
  },
  {
    name: "Selenium",
    atomicNumber: 34,
    atomicSymbol: "Se",
    atomicWeight: 78.96,
    family: "Nonmetal",
    negativeIon: 2,
  },
  {
    name: "Bromine",
    atomicNumber: 35,
    atomicSymbol: "Br",
    atomicWeight: 79.904,
    family: "Halogen",
    negativeIon: 1,
  },
  {
    name: "Krypton",
    atomicNumber: 36,
    atomicSymbol: "Kr",
    atomicWeight: 83.798,
    family: "Noble Gas",
  },
  {
    name: "Rubidium",
    atomicNumber: 37,
    atomicSymbol: "Rb",
    atomicWeight: 85.468,
    family: "Alkali Metal",
    positiveIon: 1,
  },
  {
    name: "Strontium",
    atomicNumber: 38,
    atomicSymbol: "Sr",
    atomicWeight: 87.62,
    family: "Alkaline Earth Metal",
    positiveIon: 2,
  },
  {
    name: "Yttrium",
    atomicNumber: 39,
    atomicSymbol: "Y",
    atomicWeight: 88.906,
    family: "Transition Metal",
    positiveIon: 3,
  },
  {
    name: "Zirconium",
    atomicNumber: 40,
    atomicSymbol: "Zr",
    atomicWeight: 91.224,
    family: "Transition Metal",
  },
  {
    name: "Niobium",
    atomicNumber: 41,
    atomicSymbol: "Nb",
    atomicWeight: 92.906,
    family: "Transition Metal",
  },
  {
    name: "Molybdenum",
    atomicNumber: 42,
    atomicSymbol: "Mo",
    atomicWeight: 95.96,
    family: "Transition Metal",
  },
  {
    name: "Technetium",
    atomicNumber: 43,
    atomicSymbol: "Tc",
    atomicWeight: 98,
    radioactive: true,
    family: "Transition Metal",
  },
  {
    name: "Ruthenium",
    atomicNumber: 44,
    atomicSymbol: "Ru",
    atomicWeight: 101.07,
    family: "Transition Metal",
  },
  {
    name: "Rhodium",
    atomicNumber: 45,
    atomicSymbol: "Rh",
    atomicWeight: 102.906,
    family: "Transition Metal",
  },
  {
    name: "Palladium",
    atomicNumber: 46,
    atomicSymbol: "Pd",
    atomicWeight: 106.42,
    family: "Transition Metal",
  },
  {
    name: "Silver",
    atomicNumber: 47,
    atomicSymbol: "Ag",
    atomicWeight: 107.868,
    family: "Transition Metal",
    positiveIon: 1,
  },
  {
    name: "Cadmium",
    atomicNumber: 48,
    atomicSymbol: "Cd",
    atomicWeight: 112.411,
    family: "Transition Metal",
    positiveIon: 2,
  },
  {
    name: "Indium",
    atomicNumber: 49,
    atomicSymbol: "In",
    atomicWeight: 114.818,
    family: "Metal",
    positiveIon: 3,
  },
  {
    name: "Tin",
    atomicNumber: 50,
    atomicSymbol: "Sn",
    atomicWeight: 118.71,
    family: "Metal",
  },
  {
    name: "Antimony",
    atomicNumber: 51,
    atomicSymbol: "Sb",
    atomicWeight: 121.76,
    family: "Metalloid",
  },
  {
    name: "Tellurium",
    atomicNumber: 52,
    atomicSymbol: "Te",
    atomicWeight: 127.6,
    family: "Metalloid",
    negativeIon: 2,
  },
  {
    name: "Iodine",
    atomicNumber: 53,
    atomicSymbol: "I",
    atomicWeight: 126.904,
    family: "Halogen",
    negativeIon: 1,
  },
  {
    name: "Xenon",
    atomicNumber: 54,
    atomicSymbol: "Xe",
    atomicWeight: 131.293,
    family: "Noble Gas",
  },
  {
    name: "Cesium",
    atomicNumber: 55,
    atomicSymbol: "Cs",
    atomicWeight: 132.905,
    family: "Alkali Metal",
    positiveIon: 1,
  },
  {
    name: "Barium",
    atomicNumber: 56,
    atomicSymbol: "Ba",
    atomicWeight: 137.327,
    family: "Alkaline Earth Metal",
    positiveIon: 2,
  },
  {
    name: "Lanthanum",
    atomicNumber: 57,
    atomicSymbol: "La",
    atomicWeight: 138.905,
    family: "Lanthanide",
    positiveIon: 3,
  },
  {
    name: "Cerium",
    atomicNumber: 58,
    atomicSymbol: "Ce",
    atomicWeight: 140.116,
    family: "Lanthanide",
  },
  {
    name: "Praseodymium",
    atomicNumber: 59,
    atomicSymbol: "Pr",
    atomicWeight: 140.908,
    family: "Lanthanide",
  },
  {
    name: "Neodymium",
    atomicNumber: 60,
    atomicSymbol: "Nd",
    atomicWeight: 144.242,
    family: "Lanthanide",
  },
  {
    name: "Promethium",
    atomicNumber: 61,
    atomicSymbol: "Pm",
    atomicWeight: 145,
    radioactive: true,
    family: "Lanthanide",
  },
  {
    name: "Samarium",
    atomicNumber: 62,
    atomicSymbol: "Sm",
    atomicWeight: 150.36,
    family: "Lanthanide",
  },
  {
    name: "Europium",
    atomicNumber: 63,
    atomicSymbol: "Eu",
    atomicWeight: 151.964,
    family: "Lanthanide",
  },
  {
    name: "Gadolinium",
    atomicNumber: 64,
    atomicSymbol: "Gd",
    atomicWeight: 157.25,
    family: "Lanthanide",
  },
  {
    name: "Terbium",
    atomicNumber: 65,
    atomicSymbol: "Tb",
    atomicWeight: 158.925,
    family: "Lanthanide",
  },
  {
    name: "Dysprosium",
    atomicNumber: 66,
    atomicSymbol: "Dy",
    atomicWeight: 162.5,
    family: "Lanthanide",
  },
  {
    name: "Holmium",
    atomicNumber: 67,
    atomicSymbol: "Ho",
    atomicWeight: 164.93,
    family: "Lanthanide",
  },
  {
    name: "Erbium",
    atomicNumber: 68,
    atomicSymbol: "Er",
    atomicWeight: 167.259,
    family: "Lanthanide",
  },
  {
    name: "Thulium",
    atomicNumber: 69,
    atomicSymbol: "Tm",
    atomicWeight: 168.934,
    family: "Lanthanide",
  },
  {
    name: "Ytterbium",
    atomicNumber: 70,
    atomicSymbol: "Yb",
    atomicWeight: 173.054,
    family: "Lanthanide",
  },
  {
    name: "Lutetium",
    atomicNumber: 71,
    atomicSymbol: "Lu",
    atomicWeight: 174.967,
    family: "Lanthanide",
    positiveIon: 3,
  },
  {
    name: "Hafnium",
    atomicNumber: 72,
    atomicSymbol: "Hf",
    atomicWeight: 178.49,
    family: "Transition Metal",
  },
  {
    name: "Tantalum",
    atomicNumber: 73,
    atomicSymbol: "Ta",
    atomicWeight: 180.948,
    family: "Transition Metal",
  },
  {
    name: "Tungsten",
    atomicNumber: 74,
    atomicSymbol: "W",
    atomicWeight: 183.84,
    family: "Transition Metal",
  },
  {
    name: "Rhenium",
    atomicNumber: 75,
    atomicSymbol: "Re",
    atomicWeight: 186.207,
    family: "Transition Metal",
  },
  {
    name: "Osmium",
    atomicNumber: 76,
    atomicSymbol: "Os",
    atomicWeight: 190.23,
    family: "Transition Metal",
  },
  {
    name: "Iridium",
    atomicNumber: 77,
    atomicSymbol: "Ir",
    atomicWeight: 192.217,
    family: "Transition Metal",
  },
  {
    name: "Platinum",
    atomicNumber: 78,
    atomicSymbol: "Pt",
    atomicWeight: 195.084,
    family: "Transition Metal",
  },
  {
    name: "Gold",
    atomicNumber: 79,
    atomicSymbol: "Au",
    atomicWeight: 196.967,
    family: "Transition Metal",
  },
  {
    name: "Mercury",
    atomicNumber: 80,
    atomicSymbol: "Hg",
    atomicWeight: 200.59,
    family: "Transition Metal",
  },
  {
    name: "Thallium",
    atomicNumber: 81,
    atomicSymbol: "Tl",
    atomicWeight: 204.383,
    family: "Metal",
  },
  {
    name: "Lead",
    atomicNumber: 82,
    atomicSymbol: "Pb",
    atomicWeight: 207.2,
    family: "Metal",
  },
  {
    name: "Bismuth",
    atomicNumber: 83,
    atomicSymbol: "Bi",
    atomicWeight: 208.98,
    family: "Metal",
  },
  {
    name: "Polonium",
    atomicNumber: 84,
    atomicSymbol: "Po",
    atomicWeight: 210,
    radioactive: true,
    family: "Metal",
  },
  {
    name: "Astatine",
    atomicNumber: 85,
    atomicSymbol: "At",
    atomicWeight: 210,
    radioactive: true,
    family: "Halogen",
    negativeIon: 1,
  },
  {
    name: "Radon",
    atomicNumber: 86,
    atomicSymbol: "Rn",
    atomicWeight: 222,
    radioactive: true,
    family: "Noble Gas",
  },
  {
    name: "Francium",
    atomicNumber: 87,
    atomicSymbol: "Fr",
    atomicWeight: 223,
    radioactive: true,
    family: "Alkali Metal",
    positiveIon: 1,
  },
  {
    name: "Radium",
    atomicNumber: 88,
    atomicSymbol: "Ra",
    atomicWeight: 226,
    radioactive: true,
    family: "Alkaline Earth Metal",
    positiveIon: 2,
  },
  {
    name: "Actinium",
    atomicNumber: 89,
    atomicSymbol: "Ac",
    atomicWeight: 227,
    radioactive: true,
    family: "Actinide",
    positiveIon: 3,
  },
  {
    name: "Thorium",
    atomicNumber: 90,
    atomicSymbol: "Th",
    atomicWeight: 232.038,
    radioactive: true,
    family: "Actinide",
  },
  {
    name: "Protactinium",
    atomicNumber: 91,
    atomicSymbol: "Pa",
    atomicWeight: 231.036,
    radioactive: true,
    family: "Actinide",
  },
  {
    name: "Uranium",
    atomicNumber: 92,
    atomicSymbol: "U",
    atomicWeight: 238.029,
    radioactive: true,
    family: "Actinide",
  },
  {
    name: "Neptunium",
    atomicNumber: 93,
    atomicSymbol: "Np",
    atomicWeight: 237,
    radioactive: true,
    family: "Actinide",
  },
  {
    name: "Plutonium",
    atomicNumber: 94,
    atomicSymbol: "Pu",
    atomicWeight: 244,
    radioactive: true,
    family: "Actinide",
  },
  {
    name: "Americium",
    atomicNumber: 95,
    atomicSymbol: "Am",
    atomicWeight: 243,
    radioactive: true,
    family: "Actinide",
  },
  {
    name: "Curium",
    atomicNumber: 96,
    atomicSymbol: "Cm",
    atomicWeight: 247,
    radioactive: true,
    family: "Actinide",
  },
  {
    name: "Berkelium",
    atomicNumber: 97,
    atomicSymbol: "Bk",
    atomicWeight: 247,
    radioactive: true,
    family: "Actinide",
  },
  {
    name: "Californium",
    atomicNumber: 98,
    atomicSymbol: "Cf",
    atomicWeight: 251,
    radioactive: true,
    family: "Actinide",
  },
  {
    name: "Einsteinium",
    atomicNumber: 99,
    atomicSymbol: "Es",
    atomicWeight: 252,
    radioactive: true,
    family: "Actinide",
  },
  {
    name: "Fermium",
    atomicNumber: 100,
    atomicSymbol: "Fm",
    atomicWeight: 257,
    radioactive: true,
    family: "Actinide",
  },
  {
    name: "Mendelevium",
    atomicNumber: 101,
    atomicSymbol: "Md",
    atomicWeight: 258,
    radioactive: true,
    family: "Actinide",
  },
  {
    name: "Nobelium",
    atomicNumber: 102,
    atomicSymbol: "No",
    atomicWeight: 259,
    radioactive: true,
    family: "Actinide",
  },
  {
    name: "Lawrencium",
    atomicNumber: 103,
    atomicSymbol: "Lr",
    atomicWeight: 262,
    radioactive: true,
    family: "Actinide",
    positiveIon: 3,
  },
];
for (const element of _gameData) {
  element.atomicWeight = Math.min(Math.ceil(element.atomicWeight / 50), 5);
}
export const gameData: readonly Readonly<ChemistryElement>[] = _gameData;

/** Efficient lookup table mapping atomic number to element. */
const elementLookup: Record<number, ChemistryElement> = gameData.reduce(
  (acc, element) => {
    acc[element.atomicNumber] = element;
    return acc;
  },
  {} as Record<number, ChemistryElement>
);
