export type Family =
  | "Nonmetal"
  | "Noble Gas"
  | "Alkali Metal"
  | "Alkaline Earth Metal"
  | "Metalloid"
  | "Halogen"
  | "Lanthanide"
  | "Actinide"
  | "Transition Metal"
  | "Metal";

export interface ChemistryElement {
  name: string;
  atomicNumber: number;
  atomicSymbol: string;
  atomicMass: number;
  radioactive?: true;
  family: Family;
  positiveIon?: number;
  negativeIon?: number;
}

/** Calculate mass group by dividing atomic mass by 100 and rounding up. */
export function getMassGroup(element: ChemistryElement): number {
  return Math.ceil(element.atomicMass / 100);
}

/** Calculate mass group from atomic number by looking up the element. */
export function getMassGroupFromAtomicNumber(atomicNumber: number): number {
  const element = gameData.find(e => e.atomicNumber === atomicNumber);
  if (!element) {
    throw new Error(`Element with atomic number ${atomicNumber} not found`);
  }
  return getMassGroup(element);
}

export const gameData: ReadonlyArray<Readonly<ChemistryElement>> = [
  {
    name: "Hydrogen",
    atomicNumber: 1,
    atomicSymbol: "H",
    atomicMass: 1.007,
    family: "Nonmetal",
    positiveIon: 1,
    negativeIon: 1,
  },
  {
    name: "Helium",
    atomicNumber: 2,
    atomicSymbol: "He",
    atomicMass: 4.002,
    family: "Noble Gas",
  },
  {
    name: "Lithium",
    atomicNumber: 3,
    atomicSymbol: "Li",
    atomicMass: 6.941,
    family: "Alkali Metal",
    positiveIon: 1,
  },
  {
    name: "Beryllium",
    atomicNumber: 4,
    atomicSymbol: "Be",
    atomicMass: 9.012,
    family: "Alkaline Earth Metal",
    positiveIon: 2,
  },
  {
    name: "Boron",
    atomicNumber: 5,
    atomicSymbol: "B",
    atomicMass: 10.811,
    family: "Metalloid",
  },
  {
    name: "Carbon",
    atomicNumber: 6,
    atomicSymbol: "C",
    atomicMass: 12.011,
    family: "Nonmetal",
  },
  {
    name: "Nitrogen",
    atomicNumber: 7,
    atomicSymbol: "N",
    atomicMass: 14.007,
    family: "Nonmetal",
    negativeIon: 3,
  },
  {
    name: "Oxygen",
    atomicNumber: 8,
    atomicSymbol: "O",
    atomicMass: 15.999,
    family: "Nonmetal",
    negativeIon: 2,
  },
  {
    name: "Fluorine",
    atomicNumber: 9,
    atomicSymbol: "F",
    atomicMass: 18.998,
    family: "Halogen",
    negativeIon: 1,
  },
  {
    name: "Neon",
    atomicNumber: 10,
    atomicSymbol: "Ne",
    atomicMass: 20.18,
    family: "Noble Gas",
  },
  {
    name: "Sodium",
    atomicNumber: 11,
    atomicSymbol: "Na",
    atomicMass: 22.99,
    family: "Alkali Metal",
    positiveIon: 1,
  },
  {
    name: "Magnesium",
    atomicNumber: 12,
    atomicSymbol: "Mg",
    atomicMass: 24.305,
    family: "Alkaline Earth Metal",
    positiveIon: 2,
  },
  {
    name: "Aluminum",
    atomicNumber: 13,
    atomicSymbol: "Al",
    atomicMass: 26.982,
    family: "Metal",
    positiveIon: 3,
  },
  {
    name: "Silicon",
    atomicNumber: 14,
    atomicSymbol: "Si",
    atomicMass: 28.086,
    family: "Metalloid",
  },
  {
    name: "Phosphorus",
    atomicNumber: 15,
    atomicSymbol: "P",
    atomicMass: 30.974,
    family: "Nonmetal",
    negativeIon: 3,
  },
  {
    name: "Sulfur",
    atomicNumber: 16,
    atomicSymbol: "S",
    atomicMass: 32.065,
    family: "Nonmetal",
    negativeIon: 2,
  },
  {
    name: "Chlorine",
    atomicNumber: 17,
    atomicSymbol: "Cl",
    atomicMass: 35.453,
    family: "Halogen",
    negativeIon: 1,
  },
  {
    name: "Argon",
    atomicNumber: 18,
    atomicSymbol: "Ar",
    atomicMass: 39.948,
    family: "Noble Gas",
  },
  {
    name: "Potassium",
    atomicNumber: 19,
    atomicSymbol: "K",
    atomicMass: 39.098,
    family: "Alkali Metal",
    positiveIon: 1,
  },
  {
    name: "Calcium",
    atomicNumber: 20,
    atomicSymbol: "Ca",
    atomicMass: 40.078,
    family: "Alkaline Earth Metal",
    positiveIon: 2,
  },
  {
    name: "Scandium",
    atomicNumber: 21,
    atomicSymbol: "Sc",
    atomicMass: 44.956,
    family: "Transition Metal",
    positiveIon: 3,
  },
  {
    name: "Titanium",
    atomicNumber: 22,
    atomicSymbol: "Ti",
    atomicMass: 47.867,
    family: "Transition Metal",
  },
  {
    name: "Vanadium",
    atomicNumber: 23,
    atomicSymbol: "V",
    atomicMass: 50.942,
    family: "Transition Metal",
  },
  {
    name: "Chromium",
    atomicNumber: 24,
    atomicSymbol: "Cr",
    atomicMass: 51.996,
    family: "Transition Metal",
  },
  {
    name: "Manganese",
    atomicNumber: 25,
    atomicSymbol: "Mn",
    atomicMass: 54.938,
    family: "Transition Metal",
  },
  {
    name: "Iron",
    atomicNumber: 26,
    atomicSymbol: "Fe",
    atomicMass: 55.845,
    family: "Transition Metal",
  },
  {
    name: "Cobalt",
    atomicNumber: 27,
    atomicSymbol: "Co",
    atomicMass: 58.933,
    family: "Transition Metal",
  },
  {
    name: "Nickel",
    atomicNumber: 28,
    atomicSymbol: "Ni",
    atomicMass: 58.693,
    family: "Transition Metal",
  },
  {
    name: "Copper",
    atomicNumber: 29,
    atomicSymbol: "Cu",
    atomicMass: 63.546,
    family: "Transition Metal",
  },
  {
    name: "Zinc",
    atomicNumber: 30,
    atomicSymbol: "Zn",
    atomicMass: 65.38,
    family: "Transition Metal",
  },
  {
    name: "Gallium",
    atomicNumber: 31,
    atomicSymbol: "Ga",
    atomicMass: 69.723,
    family: "Metal",
  },
  {
    name: "Germanium",
    atomicNumber: 32,
    atomicSymbol: "Ge",
    atomicMass: 72.64,
    family: "Metalloid",
  },
  {
    name: "Arsenic",
    atomicNumber: 33,
    atomicSymbol: "As",
    atomicMass: 74.922,
    family: "Metalloid",
    negativeIon: 3,
  },
  {
    name: "Selenium",
    atomicNumber: 34,
    atomicSymbol: "Se",
    atomicMass: 78.96,
    family: "Nonmetal",
    negativeIon: 2,
  },
  {
    name: "Bromine",
    atomicNumber: 35,
    atomicSymbol: "Br",
    atomicMass: 79.904,
    family: "Halogen",
    negativeIon: 1,
  },
  {
    name: "Krypton",
    atomicNumber: 36,
    atomicSymbol: "Kr",
    atomicMass: 83.798,
    family: "Noble Gas",
  },
  {
    name: "Rubidium",
    atomicNumber: 37,
    atomicSymbol: "Rb",
    atomicMass: 85.468,
    family: "Alkali Metal",
    positiveIon: 1,
  },
  {
    name: "Strontium",
    atomicNumber: 38,
    atomicSymbol: "Sr",
    atomicMass: 87.62,
    family: "Alkaline Earth Metal",
    positiveIon: 2,
  },
  {
    name: "Yttrium",
    atomicNumber: 39,
    atomicSymbol: "Y",
    atomicMass: 88.906,
    family: "Transition Metal",
    positiveIon: 3,
  },
  {
    name: "Zirconium",
    atomicNumber: 40,
    atomicSymbol: "Zr",
    atomicMass: 91.224,
    family: "Transition Metal",
  },
  {
    name: "Niobium",
    atomicNumber: 41,
    atomicSymbol: "Nb",
    atomicMass: 92.906,
    family: "Transition Metal",
  },
  {
    name: "Molybdenum",
    atomicNumber: 42,
    atomicSymbol: "Mo",
    atomicMass: 95.96,
    family: "Transition Metal",
  },
  {
    name: "Technetium",
    atomicNumber: 43,
    atomicSymbol: "Tc",
    atomicMass: 98,
    radioactive: true,
    family: "Transition Metal",
  },
  {
    name: "Ruthenium",
    atomicNumber: 44,
    atomicSymbol: "Ru",
    atomicMass: 101.07,
    family: "Transition Metal",
  },
  {
    name: "Rhodium",
    atomicNumber: 45,
    atomicSymbol: "Rh",
    atomicMass: 102.906,
    family: "Transition Metal",
  },
  {
    name: "Palladium",
    atomicNumber: 46,
    atomicSymbol: "Pd",
    atomicMass: 106.42,
    family: "Transition Metal",
  },
  {
    name: "Silver",
    atomicNumber: 47,
    atomicSymbol: "Ag",
    atomicMass: 107.868,
    family: "Transition Metal",
  },
  {
    name: "Cadmium",
    atomicNumber: 48,
    atomicSymbol: "Cd",
    atomicMass: 112.411,
    family: "Transition Metal",
  },
  {
    name: "Indium",
    atomicNumber: 49,
    atomicSymbol: "In",
    atomicMass: 114.818,
    family: "Metal",
  },
  {
    name: "Tin",
    atomicNumber: 50,
    atomicSymbol: "Sn",
    atomicMass: 118.71,
    family: "Metal",
  },
  {
    name: "Antimony",
    atomicNumber: 51,
    atomicSymbol: "Sb",
    atomicMass: 121.76,
    family: "Metalloid",
  },
  {
    name: "Tellurium",
    atomicNumber: 52,
    atomicSymbol: "Te",
    atomicMass: 127.6,
    family: "Metalloid",
    negativeIon: 2,
  },
  {
    name: "Iodine",
    atomicNumber: 53,
    atomicSymbol: "I",
    atomicMass: 126.904,
    family: "Halogen",
    negativeIon: 1,
  },
  {
    name: "Xenon",
    atomicNumber: 54,
    atomicSymbol: "Xe",
    atomicMass: 131.293,
    family: "Noble Gas",
  },
  {
    name: "Cesium",
    atomicNumber: 55,
    atomicSymbol: "Cs",
    atomicMass: 132.905,
    family: "Alkali Metal",
    positiveIon: 1,
  },
  {
    name: "Barium",
    atomicNumber: 56,
    atomicSymbol: "Ba",
    atomicMass: 137.327,
    family: "Alkaline Earth Metal",
    positiveIon: 2,
  },
  {
    name: "Lanthanum",
    atomicNumber: 57,
    atomicSymbol: "La",
    atomicMass: 138.905,
    family: "Lanthanide",
    positiveIon: 3,
  },
  {
    name: "Cerium",
    atomicNumber: 58,
    atomicSymbol: "Ce",
    atomicMass: 140.116,
    family: "Lanthanide",
  },
  {
    name: "Praseodymium",
    atomicNumber: 59,
    atomicSymbol: "Pr",
    atomicMass: 140.908,
    family: "Lanthanide",
  },
  {
    name: "Neodymium",
    atomicNumber: 60,
    atomicSymbol: "Nd",
    atomicMass: 144.242,
    family: "Lanthanide",
  },
  {
    name: "Promethium",
    atomicNumber: 61,
    atomicSymbol: "Pm",
    atomicMass: 145,
    radioactive: true,
    family: "Lanthanide",
  },
  {
    name: "Samarium",
    atomicNumber: 62,
    atomicSymbol: "Sm",
    atomicMass: 150.36,
    family: "Lanthanide",
  },
  {
    name: "Europium",
    atomicNumber: 63,
    atomicSymbol: "Eu",
    atomicMass: 151.964,
    family: "Lanthanide",
  },
  {
    name: "Gadolinium",
    atomicNumber: 64,
    atomicSymbol: "Gd",
    atomicMass: 157.25,
    family: "Lanthanide",
  },
  {
    name: "Terbium",
    atomicNumber: 65,
    atomicSymbol: "Tb",
    atomicMass: 158.925,
    family: "Lanthanide",
  },
  {
    name: "Dysprosium",
    atomicNumber: 66,
    atomicSymbol: "Dy",
    atomicMass: 162.5,
    family: "Lanthanide",
  },
  {
    name: "Holmium",
    atomicNumber: 67,
    atomicSymbol: "Ho",
    atomicMass: 164.93,
    family: "Lanthanide",
  },
  {
    name: "Erbium",
    atomicNumber: 68,
    atomicSymbol: "Er",
    atomicMass: 167.259,
    family: "Lanthanide",
  },
  {
    name: "Thulium",
    atomicNumber: 69,
    atomicSymbol: "Tm",
    atomicMass: 168.934,
    family: "Lanthanide",
  },
  {
    name: "Ytterbium",
    atomicNumber: 70,
    atomicSymbol: "Yb",
    atomicMass: 173.054,
    family: "Lanthanide",
  },
  {
    name: "Lutetium",
    atomicNumber: 71,
    atomicSymbol: "Lu",
    atomicMass: 174.967,
    family: "Lanthanide",
  },
  {
    name: "Hafnium",
    atomicNumber: 72,
    atomicSymbol: "Hf",
    atomicMass: 178.49,
    family: "Transition Metal",
  },
  {
    name: "Tantalum",
    atomicNumber: 73,
    atomicSymbol: "Ta",
    atomicMass: 180.948,
    family: "Transition Metal",
  },
  {
    name: "Tungsten",
    atomicNumber: 74,
    atomicSymbol: "W",
    atomicMass: 183.84,
    family: "Transition Metal",
  },
  {
    name: "Rhenium",
    atomicNumber: 75,
    atomicSymbol: "Re",
    atomicMass: 186.207,
    family: "Transition Metal",
  },
  {
    name: "Osmium",
    atomicNumber: 76,
    atomicSymbol: "Os",
    atomicMass: 190.23,
    family: "Transition Metal",
  },
  {
    name: "Iridium",
    atomicNumber: 77,
    atomicSymbol: "Ir",
    atomicMass: 192.217,
    family: "Transition Metal",
  },
  {
    name: "Platinum",
    atomicNumber: 78,
    atomicSymbol: "Pt",
    atomicMass: 195.084,
    family: "Transition Metal",
  },
  {
    name: "Gold",
    atomicNumber: 79,
    atomicSymbol: "Au",
    atomicMass: 196.967,
    family: "Transition Metal",
  },
  {
    name: "Mercury",
    atomicNumber: 80,
    atomicSymbol: "Hg",
    atomicMass: 200.59,
    family: "Transition Metal",
  },
  {
    name: "Thallium",
    atomicNumber: 81,
    atomicSymbol: "Tl",
    atomicMass: 204.383,
    family: "Metal",
  },
  {
    name: "Lead",
    atomicNumber: 82,
    atomicSymbol: "Pb",
    atomicMass: 207.2,
    family: "Metal",
  },
  {
    name: "Bismuth",
    atomicNumber: 83,
    atomicSymbol: "Bi",
    atomicMass: 208.98,
    family: "Metal",
  },
  {
    name: "Polonium",
    atomicNumber: 84,
    atomicSymbol: "Po",
    atomicMass: 210,
    radioactive: true,
    family: "Metalloid",
  },
  {
    name: "Astatine",
    atomicNumber: 85,
    atomicSymbol: "At",
    atomicMass: 210,
    radioactive: true,
    family: "Noble Gas",
    negativeIon: 1,
  },
  {
    name: "Radon",
    atomicNumber: 86,
    atomicSymbol: "Rn",
    atomicMass: 222,
    radioactive: true,
    family: "Alkali Metal",
  },
  {
    name: "Francium",
    atomicNumber: 87,
    atomicSymbol: "Fr",
    atomicMass: 223,
    radioactive: true,
    family: "Alkaline Earth Metal",
    positiveIon: 1,
  },
  {
    name: "Radium",
    atomicNumber: 88,
    atomicSymbol: "Ra",
    atomicMass: 226,
    radioactive: true,
    family: "Actinide",
    positiveIon: 2,
  },
  {
    name: "Actinium",
    atomicNumber: 89,
    atomicSymbol: "Ac",
    atomicMass: 227,
    radioactive: true,
    family: "Actinide",
    positiveIon: 3,
  },
  {
    name: "Thorium",
    atomicNumber: 90,
    atomicSymbol: "Th",
    atomicMass: 232.038,
    radioactive: true,
    family: "Actinide",
  },
  {
    name: "Protactinium",
    atomicNumber: 91,
    atomicSymbol: "Pa",
    atomicMass: 231.036,
    radioactive: true,
    family: "Actinide",
  },
  {
    name: "Uranium",
    atomicNumber: 92,
    atomicSymbol: "U",
    atomicMass: 238.029,
    radioactive: true,
    family: "Actinide",
  },
  {
    name: "Neptunium",
    atomicNumber: 93,
    atomicSymbol: "Np",
    atomicMass: 237,
    radioactive: true,
    family: "Actinide",
  },
  {
    name: "Plutonium",
    atomicNumber: 94,
    atomicSymbol: "Pu",
    atomicMass: 244,
    radioactive: true,
    family: "Actinide",
  },
  {
    name: "Americium",
    atomicNumber: 95,
    atomicSymbol: "Am",
    atomicMass: 243,
    radioactive: true,
    family: "Actinide",
  },
  {
    name: "Curium",
    atomicNumber: 96,
    atomicSymbol: "Cm",
    atomicMass: 247,
    radioactive: true,
    family: "Actinide",
  },
  {
    name: "Berkelium",
    atomicNumber: 97,
    atomicSymbol: "Bk",
    atomicMass: 247,
    radioactive: true,
    family: "Actinide",
  },
  {
    name: "Californium",
    atomicNumber: 98,
    atomicSymbol: "Cf",
    atomicMass: 251,
    radioactive: true,
    family: "Actinide",
  },
  {
    name: "Einsteinium",
    atomicNumber: 99,
    atomicSymbol: "Es",
    atomicMass: 252,
    radioactive: true,
    family: "Actinide",
  },
  {
    name: "Fermium",
    atomicNumber: 100,
    atomicSymbol: "Fm",
    atomicMass: 257,
    radioactive: true,
    family: "Actinide",
  },
  {
    name: "Mendelevium",
    atomicNumber: 101,
    atomicSymbol: "Md",
    atomicMass: 258,
    radioactive: true,
    family: "Actinide",
  },
  {
    name: "Nobelium",
    atomicNumber: 102,
    atomicSymbol: "No",
    atomicMass: 259,
    radioactive: true,
    family: "Actinide",
  },
  {
    name: "Lawrencium",
    atomicNumber: 103,
    atomicSymbol: "Lr",
    atomicMass: 262,
    radioactive: true,
    family: "Actinide",
  },
];
